module.exports = {
  weibo: {
    toWangEditor: function () {
      var _this = this;
      var html = [];
      for (var i = 0; i < _this.emotions.length; i++) {
        html.push({
          alt: _this.emotions[i].value,
          src: _this.emotions[i].url
        })
      }
      return html
    },
    emotions: [{
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/f6/2018new_aini_org.png",
        "value": "[鐖变綘]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/83/2018new_kuxiao_org.png",
        "value": "[鍏佹偛]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/ee/2018new_beishang_org.png",
        "value": "[鎮蹭激]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/49/2018new_chijing_org.png",
        "value": "[鍚冩儕]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/71/2018new_touxiao_org.png",
        "value": "[鍋风瑧]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/b8/2018new_ningwen_org.png",
        "value": "[鐤戦棶]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/c1/2018new_youhengheng_org.png",
        "value": "[鍙冲摷鍝糫"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/86/2018new_hufen02_org.png",
        "value": "[浜掔矇]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/ae/2018new_ding_org.png",
        "value": "[椤禲"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/10/2018new_wu_org.png",
        "value": "[姹"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/c1/2018new_haixiu_org.png",
        "value": "[瀹崇緸]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/96/2018new_kelian_org.png",
        "value": "[鍙€淽"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/aa/2018new_shiwang_org.png",
        "value": "[澶辨湜]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/3b/2018new_shengbing_org.png",
        "value": "[鐢熺梾]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/c9/2018new_chongjing_org.png",
        "value": "[鎲ф啲]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/a3/2018new_heixian_org.png",
        "value": "[榛戠嚎]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/40/2018new_kouzhao_org.png",
        "value": "[鎰熷啋]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/2c/2018new_qinqin_org.png",
        "value": "[浜蹭翰]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/aa/2018new_bingbujiandan_org.png",
        "value": "[骞朵笉绠€鍗昡"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/07/2018new_yun_org.png",
        "value": "[鏅昡"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/01/2018new_chigua_org.png",
        "value": "[鍚冪摐]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/cb/2018new_dalian_org.png",
        "value": "[鎵撹劯]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/09/2018new_keai_org.png",
        "value": "[鍙埍]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/28/2018new_han_org.png",
        "value": "[姹梋"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/2d/2018new_xiaoerbuyu_org.png",
        "value": "[绗戣€屼笉璇璢"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/fa/2018new_chanzui_org.png",
        "value": "[棣嬪槾]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/17/2018new_zhuakuang_org.png",
        "value": "[鎶撶媯]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/1e/2018new_taikaixin_org.png",
        "value": "[澶紑蹇僝"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/4d/2018new_huaixiao_org.png",
        "value": "[鍧忕瑧]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/08/2018new_tu_org.png",
        "value": "[鍚怾"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/9d/2018new_huaxin_org.png",
        "value": "[鑹瞉"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/e3/2018new_weixioa02_org.png",
        "value": "[寰瑧]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/4a/2018new_xiaoku_thumb.png",
        "value": "[绗慶ry]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/c4/2018new_ku_org.png",
        "value": "[閰穄"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/a2/2018new_shuai_org.png",
        "value": "[琛癩"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/7c/2018new_heng_org.png",
        "value": "[鍝糫"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/30/2018new_sikao_org.png",
        "value": "[鎬濊€僝"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/f6/2018new_nu_org.png",
        "value": "[鎬抅"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/6e/2018new_guzhang_org.png",
        "value": "[榧撴帉]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/a2/2018new_qian_org.png",
        "value": "[閽盷"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/3c/2018new_kun_org.png",
        "value": "[鍥癩"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/3e/2018new_tianping_org.png",
        "value": "[鑸斿睆]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/fd/2018new_baibai_org.png",
        "value": "[鎷滄嫓]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/b0/2018new_xu_org.png",
        "value": "[鍢榏"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/43/2018new_zuohengheng_org.png",
        "value": "[宸﹀摷鍝糫"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/9e/2018new_yinxian_org.png",
        "value": "[闃撮櫓]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/87/2018new_zhouma_org.png",
        "value": "[鎬掗獋]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/2a/2018new_wenhao_org.png",
        "value": "[璐硅В]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/43/2018new_jiyan_org.png",
        "value": "[鎸ょ溂]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/62/2018new_bizui_org.png",
        "value": "[闂槾]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/33/2018new_xixi_org.png",
        "value": "[鍢诲樆]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/55/2018new_dahaqian_org.png",
        "value": "[鍝堟瑺]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/a5/2018new_weiqu_org.png",
        "value": "[濮斿眻]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/6e/2018new_leimu_org.png",
        "value": "[娉猐"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/da/2018new_bishi_org.png",
        "value": "[閯欒]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/8f/2018new_haha_org.png",
        "value": "[鍝堝搱]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/dd/2018new_shayan_org.png",
        "value": "[鍌荤溂]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/9a/2018new_wabi_thumb.png",
        "value": "[鎸栭蓟]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/e2/2018new_shuijiao_thumb.png",
        "value": "[鐫"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/ef/2018new_landelini_org.png",
        "value": "[鐧界溂]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/1e/2018new_no_org.png",
        "value": "[NO]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/e6/2018new_zan_org.png",
        "value": "[璧瀅"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/e7/2018new_zuoyi_org.png",
        "value": "[浣滄彇]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/1d/2018new_hahashoushi_org.png",
        "value": "[haha]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/e9/2018new_woshou_org.png",
        "value": "[鎻℃墜]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/86/2018new_quantou_org.png",
        "value": "[鎷冲ご]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/45/2018new_ok_org.png",
        "value": "[ok]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/8a/2018new_good_org.png",
        "value": "[good]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/3d/2018new_ruo_org.png",
        "value": "[寮盷"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/9f/2018new_jiayou_org.png",
        "value": "[鍔犳补]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/42/2018new_guolai_org.png",
        "value": "[鏉"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/29/2018new_ye_org.png",
        "value": "[鑰禲"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/6d/2018new_zhongguozan_org.png",
        "value": "[涓浗璧瀅"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/57/2018new_guanggao_thumb.png",
        "value": "[骞垮憡]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/22/2018new_erha_org.png",
        "value": "[浜屽搱]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/7b/2018new_miaomiao_org.png",
        "value": "[鍠靛柕]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/a1/2018new_doge02_org.png",
        "value": "[doge]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/42/2018new_baobao_org.png",
        "value": "[鎶辨姳]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/62/2018new_tanshou_org.png",
        "value": "[鎽婃墜]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/75/2018new_gui_org.png",
        "value": "[璺簡]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/fe/2018zhongqiu_xiaoxiannv_org.png",
        "value": "[灏忎粰濂砞"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/ca/qixi2018_xiaoxinxin_org.png",
        "value": "[缁欎綘灏忓績蹇僝"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/31/mickey_bixin_org.png",
        "value": "[绫冲姣斿績]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/17/mickey_aini_org.png",
        "value": "[绫冲鐖变綘]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/76/hot_star171109_org.png",
        "value": "[鏄熸槦]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/f9/hot_halfstar_org.png",
        "value": "[鍗婃槦]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/ff/hot_blankstar_org.png",
        "value": "[绌烘槦]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/0a/2018new_nanhai_org.png",
        "value": "[鐢峰鍎縘"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/39/2018new_nvhai_org.png",
        "value": "[濂冲鍎縘"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/fa/lxhtouxiao_thumb.gif",
        "value": "[鍋蜂箰]"
      },
      {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/e0/2018new_xizi_org.png",
        "value": "[鍠淽"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/aa/2018new_xiongmao_org.png",
        "value": "[鐔婄尗]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/d4/2018new_xianhua_org.png",
        "value": "[椴滆姳]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/60/horse2_org.gif",
        "value": "[绁為┈]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/cb/2018new_lvsidai_org.png",
        "value": "[缁夸笣甯"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/6c/2018new_weiguan_org.png",
        "value": "[鍥磋]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/61/2018new_yunduo_org.png",
        "value": "[娴簯]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/78/2018new_xiangji_org.png",
        "value": "[鐓х浉鏈篯"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/b0/mdcg_org.gif",
        "value": "[椹埌鎴愬姛]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/3b/2018new_caonima_org.png",
        "value": "[鑽夋偿椹琞"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/d5/2018new_yueliang_org.png",
        "value": "[鏈堜寒]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/46/2018new_xinlang_org.png",
        "value": "[娴猐"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/ac/lxhqiuguanzhu_org.gif",
        "value": "[姹傚叧娉╙"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/1f/2018new_yinyue_org.png",
        "value": "[闊充箰]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/14/2018new_weiwu_org.png",
        "value": "[濞佹]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/c6/2018new_tuzi_org.png",
        "value": "[鍏斿瓙]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/1c/2018new_zhutou_thumb.png",
        "value": "[鐚ご]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/c7/2018new_weifeng_thumb.png",
        "value": "[寰]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/df/lxhxiudada_org.gif",
        "value": "[缇炲棐鍡抅"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/36/2018new_geili_org.png",
        "value": "[缁欏姏]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/7e/2018new_yu_org.png",
        "value": "[涓嬮洦]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/16/2018new_lazhu_org.png",
        "value": "[铚＄儧]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/e2/zhajibeer_org.gif",
        "value": "[鐐搁浮鍟ら厭]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/cd/2018new_taiyang_org.png",
        "value": "[澶槼]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/be/remen_zuiyou180605_org.png",
        "value": "[鏈€鍙砞"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/40/2018new_ganbei_org.png",
        "value": "[骞叉澂]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/32/lxhwahaha_org.gif",
        "value": "[绗戝搱鍝圿"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/74/lxhainio_org.gif",
        "value": "[濂界埍鍝"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/d6/lxhlike_thumb.gif",
        "value": "[濂藉枩娆"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/c6/2018new_aoteman_org.png",
        "value": "[濂ョ壒鏇糫"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/b7/2018new_shachenbao_org.png",
        "value": "[娌欏皹鏆碷"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/00/lxhzan_thumb.gif",
        "value": "[璧炲晩]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/f9/2018new_dangao_org.png",
        "value": "[铔嬬硶]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/d6/2018new_feizao_thumb.png",
        "value": "[鑲ョ殏]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/48/2018new_huatong_org.png",
        "value": "[璇濈瓛]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/8e/2018new_zhong_org.png",
        "value": "[閽焆"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/4a/2018new_feiji_org.png",
        "value": "[椋炴満]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/64/2018new_weibo_org.png",
        "value": "[鍥磋剸]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/6c/2018new_xinsui_org.png",
        "value": "[浼ゅ績]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/8a/2018new_xin_org.png",
        "value": "[蹇僝"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/0e/2018new_liwu_org.png",
        "value": "[绀肩墿]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/41/zz2_org.gif",
        "value": "[缁嘳"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/a1/2018new_kulou_org.png",
        "value": "[楠烽珔]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/10/2018zhongqiu_yuebing_org.png",
        "value": "[浜斾粊鏈堥ゼ]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/ca/qixi2018_xiaoxinxin_org.png",
        "value": "[缁欎綘灏忓績蹇僝"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/0b/qixi2018_chigouliang_org.png",
        "value": "[鍚冪嫍绮甝"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/83/2018newyear_richdog_org.gif",
        "value": "[寮楄幈瑙侀挶鐪煎紑]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/fe/kanzhangv2_org.gif",
        "value": "[鐪嬫定]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/c5/kandiev2_org.gif",
        "value": "[鐪嬭穼]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/ec/eventtravel_org.gif",
        "value": "[甯︾潃寰崥鍘绘梾琛宂"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/00/lxhzan_org.gif",
        "value": "[璧炲晩]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/d6/lxhlike_org.gif",
        "value": "[濂藉枩娆"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/b5/mickey_xihuan_org.png",
        "value": "[绫冲鍠滄]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/84/mickey_feiwen_org.png",
        "value": "[绫冲椋炲惢]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/81/mickey_daku_org.png",
        "value": "[绫冲澶у摥]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/31/mickey_bixin_org.png",
        "value": "[绫冲姣斿績]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/7d/mickey_aloha_org.png",
        "value": "[Aloha]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/17/mickey_aini_org.png",
        "value": "[绫冲鐖变綘]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/44/fulian3_gangtiexia01_org.png",
        "value": "[閽㈤搧渚燷"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/1e/fulian3_meiguoduizhang01_org.png",
        "value": "[缇庡浗闃熼暱]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/5a/fulian3_haoke01_org.png",
        "value": "[娴╁厠]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/1f/fulian3_leishen01_org.png",
        "value": "[闆风]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/69/fulian3_luoji01_org.png",
        "value": "[娲涘熀]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/7e/fulian3_zhizhuxia01_org.png",
        "value": "[铚樿洓渚燷"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/a3/fulian3_qiyiboshi01_org.png",
        "value": "[濂囧紓鍗氬＋]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/78/fulian3_heiguafu01_org.png",
        "value": "[榛戝濡嘳"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/5e/fulian3_dongbing01_org.png",
        "value": "[鍐叺]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/de/fulian3_gelute01_org.png",
        "value": "[鏍奸瞾鐗筣"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/b6/manwei_yiren_org.png",
        "value": "[铓佷汉]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/84/manwei_huangfengnv_org.png",
        "value": "[榛勮渹濂砞"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/08/dorahaose_org.gif",
        "value": "[鍝嗗暒A姊﹁姳蹇僝"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/c7/dorahaipa_org.gif",
        "value": "[鍝嗗暒A姊﹀鎬昡"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/f0/dorachijing_org.gif",
        "value": "[鍝嗗暒A姊﹀悆鎯奭"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/61/dorahan_org.gif",
        "value": "[鍝嗗暒A姊︽睏]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/9e/jqmweixiao_org.gif",
        "value": "[鍝嗗暒A姊﹀井绗慮"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/ef/jqmbwtxing_org.gif",
        "value": "[浼存垜鍚岃]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/29/jiqimaojingxiang_org.gif",
        "value": "[闈欓寰瑧]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/8e/jiqimaodaxiong_org.gif",
        "value": "[澶ч泟寰瑧]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/2f/jiqimaopanghu_org.gif",
        "value": "[鑳栬檸寰瑧]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/21/jiqimaoxiaofu_org.gif",
        "value": "[灏忓か寰瑧]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/54/dora_xiao_org.png",
        "value": "[鍝嗗暒A姊︾瑧]"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/96/dora_wunai_org.png",
        "value": "[鍝嗗暒A姊︽棤濂圿"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/21/dora_meiwei_org.png",
        "value": "[鍝嗗暒A姊︾編鍛砞"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/df/dora_kaixin_org.png",
        "value": "[鍝嗗暒A姊﹀紑蹇僝"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/e0/dora_qinqin_org.png",
        "value": "[鍝嗗暒A姊︿翰浜瞉"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/f0/xhrnew_weixiao_org.png",
        "value": "[灏忛粍浜哄井绗慮"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/63/xhrnew_jiandaoshou_org.png",
        "value": "[灏忛粍浜哄壀鍒€鎵媇"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/b2/xhrnew_buxie_org.png",
        "value": "[灏忛粍浜轰笉灞慮"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/41/xhrnew_gaoxing_org.png",
        "value": "[灏忛粍浜洪珮鍏碷"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/fd/xhrnew_jingya_thumb.png",
        "value": "[灏忛粍浜烘儕璁禲"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/79/xhrnew_weiqu_org.png",
        "value": "[灏忛粍浜哄灞圿"
      },
      {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/be/xhrnew_huaixiao_thumb.png",
        "value": "[灏忛粍浜哄潖绗慮"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/e2/xhrnew_baiyan_org.png",
        "value": "[灏忛粍浜虹櫧鐪糫"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/15/xhrnew_wunai_org.png",
        "value": "[灏忛粍浜烘棤濂圿"
      }, {
        "url": "http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/c8/xhrnew_deyi_org.png",
        "value": "[灏忛粍浜哄緱鎰廬"
      }
    ]
  },


  xinlang: {
    toWangEditor: function () {
      var _this = this;
      var html = [];
      for (var i = 0; i < _this.emotions.length; i++) {
        html.push({
          alt: _this.emotions[i].value,
          src: _this.emotions[i].icon
        })
      }
      return html
    },
    emotions: [{
      icon: "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/7a/shenshou_thumb.gif",
      value: "[鑽夋偿椹琞"
    }, {
      icon: "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/60/horse2_thumb.gif",
      value: "[绁為┈]"
    }, {
      icon: "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/bc/fuyun_thumb.gif",
      value: "[娴簯]"
    }, {
      icon: "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/c9/geili_thumb.gif",
      value: "[缁欏姏]"
    }, {
      icon: "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/f2/wg_thumb.gif",
      value: "[鍥磋]"
    }, {
      icon: "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/70/vw_thumb.gif",
      value: "[濞佹]"
    }, {
      icon: "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/6e/panda_thumb.gif",
      value: "[鐔婄尗]"
    }, {
      icon: "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/81/rabbit_thumb.gif",
      value: "[鍏斿瓙]"
    }, {
      icon: "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/bc/otm_thumb.gif",
      value: "[濂ョ壒鏇糫"
    }, {
      icon: "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/15/j_thumb.gif",
      value: "[鍥"
    }, {
      icon: "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/89/hufen_thumb.gif",
      value: "[浜掔矇]"
    }, {
      icon: "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/c4/liwu_thumb.gif",
      value: "[绀肩墿]"
    }, {
      icon: "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/ac/smilea_thumb.gif",
      value: "[鍛靛懙]"
    }, {
      icon: "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/0b/tootha_thumb.gif",
      value: "[鍢诲樆]"
    }, {
      icon: "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/6a/laugh.gif",
      value: "[鍝堝搱]"
    }, {
      icon: "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/14/tza_thumb.gif",
      value: "[鍙埍]"
    }, {
      icon: "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/af/kl_thumb.gif",
      value: "[鍙€淽"
    }, {
      icon: "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/a0/kbsa_thumb.gif",
      value: "[鎸栭蓟灞嶿"
    }, {
      icon: "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/f4/cj_thumb.gif",
      value: "[鍚冩儕]"
    }, {
      icon: "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/6e/shamea_thumb.gif",
      value: "[瀹崇緸]"
    }, {
      icon: "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/c3/zy_thumb.gif",
      value: "[鎸ょ溂]"
    }, {
      icon: "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/29/bz_thumb.gif",
      value: "[闂槾]"
    }, {
      icon: "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/71/bs2_thumb.gif",
      value: "[閯欒]"
    }, {
      icon: "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/6d/lovea_thumb.gif",
      value: "[鐖变綘]"
    }, {
      icon: "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/9d/sada_thumb.gif",
      value: "[娉猐"
    }, {
      icon: "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/19/heia_thumb.gif",
      value: "[鍋风瑧]"
    }, {
      icon: "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/8f/qq_thumb.gif",
      value: "[浜蹭翰]"
    }, {
      icon: "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/b6/sb_thumb.gif",
      value: "[鐢熺梾]"
    }, {
      icon: "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/58/mb_thumb.gif",
      value: "[澶紑蹇僝"
    }, {
      icon: "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/17/ldln_thumb.gif",
      value: "[鎳掑緱鐞嗕綘]"
    }, {
      icon: "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/98/yhh_thumb.gif",
      value: "[鍙冲摷鍝糫"
    }, {
      icon: "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/6d/zhh_thumb.gif",
      value: "[宸﹀摷鍝糫"
    }, {
      icon: "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/a6/x_thumb.gif",
      value: "[鍢榏"
    }, {
      icon: "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/af/cry.gif",
      value: "[琛癩"
    }, {
      icon: "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/73/wq_thumb.gif",
      value: "[濮斿眻]"
    }, {
      icon: "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/9e/t_thumb.gif",
      value: "[鍚怾"
    }, {
      icon: "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/f3/k_thumb.gif",
      value: "[鎵撳搱娆燷"
    }, {
      icon: "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/27/bba_thumb.gif",
      value: "[鎶辨姳]"
    }, {
      icon: "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/7c/angrya_thumb.gif",
      value: "[鎬抅"
    }, {
      icon: "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/5c/yw_thumb.gif",
      value: "[鐤戦棶]"
    }, {
      icon: "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/a5/cza_thumb.gif",
      value: "[棣嬪槾]"
    }, {
      icon: "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/70/88_thumb.gif",
      value: "[鎷滄嫓]"
    }, {
      icon: "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/e9/sk_thumb.gif",
      value: "[鎬濊€僝"
    }, {
      icon: "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/24/sweata_thumb.gif",
      value: "[姹梋"
    }, {
      icon: "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/7f/sleepya_thumb.gif",
      value: "[鍥癩"
    }, {
      icon: "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/6b/sleepa_thumb.gif",
      value: "[鐫¤]"
    }, {
      icon: "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/90/money_thumb.gif",
      value: "[閽盷"
    }, {
      icon: "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/0c/sw_thumb.gif",
      value: "[澶辨湜]"
    }, {
      icon: "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/40/cool_thumb.gif",
      value: "[閰穄"
    }, {
      icon: "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/8c/hsa_thumb.gif",
      value: "[鑺卞績]"
    }, {
      icon: "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/49/hatea_thumb.gif",
      value: "[鍝糫"
    }, {
      icon: "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/36/gza_thumb.gif",
      value: "[榧撴帉]"
    }, {
      icon: "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/d9/dizzya_thumb.gif",
      value: "[鏅昡"
    }, {
      icon: "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/1a/bs_thumb.gif",
      value: "[鎮蹭激]"
    }, {
      icon: "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/62/crazya_thumb.gif",
      value: "[鎶撶媯]"
    }, {
      icon: "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/91/h_thumb.gif",
      value: "[榛戠嚎]"
    }, {
      icon: "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/6d/yx_thumb.gif",
      value: "[闃撮櫓]"
    }, {
      icon: "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/89/nm_thumb.gif",
      value: "[鎬掗獋]"
    }, {
      icon: "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/40/hearta_thumb.gif",
      value: "[蹇僝"
    }, {
      icon: "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/ea/unheart.gif",
      value: "[浼ゅ績]"
    }, {
      icon: "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/58/pig.gif",
      value: "[鐚ご]"
    }, {
      icon: "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/d6/ok_thumb.gif",
      value: "[ok]"
    }, {
      icon: "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/d9/ye_thumb.gif",
      value: "[鑰禲"
    }, {
      icon: "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/d8/good_thumb.gif",
      value: "[good]"
    }, {
      icon: "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/c7/no_thumb.gif",
      value: "[涓嶈]"
    }, {
      icon: "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/d0/z2_thumb.gif",
      value: "[璧瀅"
    }, {
      icon: "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/40/come_thumb.gif",
      value: "[鏉"
    }, {
      icon: "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/d8/sad_thumb.gif",
      value: "[寮盷"
    }, {
      icon: "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/91/lazu_thumb.gif",
      value: "[铚＄儧]"
    }, {
      icon: "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/6a/cake.gif",
      value: "[铔嬬硶]"
    }, {
      icon: "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/d3/clock_thumb.gif",
      value: "[閽焆"
    }, {
      icon: "http://img.t.sinajs.cn/t35/style/images/common/face/ext/normal/1b/m_thumb.gif",
      value: "[璇濈瓛]"
    }]
  }
}
